server:
  servlet:
    context-path: /
spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
control-panel:
  auth:
    username: gesucca
    password: $2a$10$xqpm6aaPyyulJoAshw00OeSrTAw4bLqAVqD/ilwCl6LEHgflTPJxe